# Generated by Django 4.2.16 on 2024-10-31 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=122)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('pic', models.ImageField(upload_to='./Images')),
            ],
        ),
    ]
